---
name: Rebar3 Dependency Submission
# yamllint disable-line rule:line-length
description: Calculates dependencies for Rebar3 and submits the list to the GitHub Dependency Submission API

# TBD(erlef): author
author: Kivra

branding:
  icon: arrow-up
  color: blue

inputs:
  token:
    description: GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner
    required: false
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Verify Dependency Submission Tool Provenance
      env:
        TAG: 1.0.0-beta.3 # release-TAG
        # TBD(erlef): update REPO
        REPO: kivra/rebar3-dependency-submission
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh attestation verify \
          "oci://ghcr.io/${REPO}:${TAG}" \
          --repo "${REPO}" \
          --source-ref "refs/tags/${TAG}"
      shell: bash
      working-directory: ${{ runner.temp }}

    - name: Run Dependency Submission
      env:
        TAG: 1.0.0-beta.3 # release-TAG
        # TBD(erlef): update REPO
        REPO: kivra/rebar3-dependency-submission
      run: |
        docker run \
          --rm \
          --env GITHUB_TOKEN="${{ inputs.token }}" \
          --env GITHUB_REPOSITORY="${{ github.repository }}" \
          --env GITHUB_JOB="${{ github.job }}" \
          --env GITHUB_REF="${{ github.ref }}" \
          --env GITHUB_RUN_ID="${{ github.run_id }}" \
          --env GITHUB_SHA="${{ github.sha }}" \
          --env GITHUB_WORKFLOW="${{ github.workflow }}" \
          --volume "${{ github.workspace }}:/app" \
          "ghcr.io/${REPO}:${TAG}"
      shell: bash
