## SPDX-License-Identifier: Apache-2.0
## SPDX-FileCopyrightText: 2026 Kivra AB
---
name: Rebar3 Dependency Submission
# yamllint disable-line rule:line-length
description: Calculates dependencies for Rebar3 and submits the list to the GitHub Dependency Submission API

# TBD(erlef): author
author: Kivra

branding:
  icon: arrow-up
  color: blue

inputs:
  token:
    description: GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner
    required: false
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Download Dependency Submission Tool
      env:
        TAG: v1.0.0-beta.9 # release-TAG
        # TBD(erlef): update REPO
        REPO: kivra/rebar3-dependency-submission
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh release download \
          "${TAG}" \
          --repo "${REPO}" \
          --pattern rebar3_dependency_submission \
          --output rebar3_dependency_submission
      shell: bash
      working-directory: ${{ runner.temp }}

    - name: Verify Dependency Submission Tool Provenance
      env:
        TAG: v1.0.0-beta.9 # release-TAG
        # TBD(erlef): update REPO
        REPO: kivra/rebar3-dependency-submission
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh attestation verify \
          --repo "${REPO}" \
          --source-ref refs/tags/"${TAG}" \
          rebar3_dependency_submission
      shell: bash
      working-directory: ${{ runner.temp }}

    - name: Make Tool Executable
      run: chmod +x rebar3_dependency_submission
      shell: bash
      working-directory: ${{ runner.temp }}

    - name: Install Erlang
      uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
      with:
        # Try to keep consistent with ci.yaml and release.yaml
        otp-version: 28.3.1
        rebar3-version: 3.26.0

    - name: Run Dependency Submission
      run: |
        "${{ runner.temp }}"/rebar3_dependency_submission --token "${{ inputs.token }}"
      shell: bash
