---
name: Release
description: Release

inputs:
  tag:
    required: true
  github_actor:
    required: true
  github_token:
    required: true

runs:
  using: composite

  steps:
    - name: Set up Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}

    - name: Build Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      id: build-push-action
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ inputs.tag }}

    - name: Run Docker image
      run: |
        docker run \
          --rm \
          --volume "${{ github.workspace }}:${{ github.workspace }}" \
          --env GITHUB_API_URL="${GITHUB_API_URL}" \
          --env GITHUB_SERVER_URL="${GITHUB_SERVER_URL}" \
          --env GITHUB_WORKFLOW="${GITHUB_WORKFLOW}" \
          --env GITHUB_JOB="${GITHUB_JOB}" \
          --env GITHUB_REF="${GITHUB_REF}" \
          --env GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
          --env GITHUB_RUN_ID="${GITHUB_RUN_ID}" \
          --env GITHUB_SHA="${GITHUB_SHA}" \
          --env GITHUB_TOKEN="${{ inputs.github_token }}" \
          "ghcr.io/${{ github.repository }}@${{ steps.build-push-action.outputs.digest }}"
      shell: bash

    - name: Create a GitHub release
      if: github.event_name == 'workflow_dispatch' && inputs.tag != ''
      run: |
        gh release create ${{ inputs.tag }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Update GitHub Release
      if: github.event_name == 'workflow_dispatch' && inputs.tag != ''
      run: |
        gh release edit ${{ inputs.tag }} \
          --notes "$(gh release view ${{ inputs.tag }} --json body --template '{{.body}}')

          ---
          **Docker Image:** ghcr.io/${{ github.repository }}:${{ inputs.tag }}
          **Digest:** \`${{ steps.build-push-action.outputs.digest }}\`"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
