---
on:
  - pull_request

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Erlang
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore from cache
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        id: restore-cache
        with:
          path: |
            _build
            ~/.cache/rebar3
            !_build/test/logs
          key: "cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}-${{hashFiles('rebar.config')}}"

      - name: Continuous Integration
        run: |
          git config --global url."https://github.com/".insteadOf 'git@github.com:'
          rebar3 ci

      - name: Save to cache
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: |
            _build
            ~/.cache/rebar3
            !_build/test/logs
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

      - name: Submit snapshot
        run: |
          ./_build/default/bin/rebar3_dependency_submission --token ${{ github.token }}

      - name: Test 'scripts'
        run: |
          mkdir -p "${HOME}"/.ssh
          eval "$(ssh-agent -s)"

          ./scripts/build-and-run.sh
