---
name: Continuous Integration / Release

on:
  pull_request:

  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write
  actions: write
  packages: write
  id-token: write
  attestations: write

jobs:
  continuous_integration:
    name: Continuous Integration / Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Erlang
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        id: setup-beam
        with:
          # Try to keep consistent with action.yaml
          otp-version: 28.3.1
          rebar3-version: 3.26.0

      - name: Restore Erlang cache
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: |
            _build
            ~/.cache/rebar3
            !_build/test/logs
          key: unused
          # Pulls generically: without run id or run attempt
          # Otherwise, if trying to use the same key cache/save later errors out
          restore-keys: "cache-for\
                         -os-${{ runner.os }}\
                         -otp-${{ steps.setup-beam.outputs.otp-version }}\
                         -rebar3-${{ steps.setup-beam.outputs.rebar3-version }}\
                         -hash-${{ hashFiles('rebar.lock') }}-${{ hashFiles('rebar.config') }}\
                         -"

      - name: Run Continuous Integration
        run: |
          git config \
            --global url."https://github.com/".insteadOf 'git@github.com:'
          rebar3 ci

      - name: Save Erlang cache
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: |
            _build
            ~/.cache/rebar3
            !_build/test/logs
          # Saves specifically: with run id and run attempt
          key: "cache-for\
                -os-${{ runner.os }}\
                -otp-${{ steps.setup-beam.outputs.otp-version }}\
                -rebar3-${{ steps.setup-beam.outputs.rebar3-version }}\
                -hash-${{ hashFiles('rebar.lock') }}-${{ hashFiles('rebar.config') }}\
                -${{ github.run_id }}-${{ github.run_attempt }}"

      - name: Test local dependency submission
        run: |
          ./_build/default/bin/rebar3_dependency_submission \
            --token "${{ secrets.GITHUB_TOKEN }}"

      - name: Attest provenance
        id: attest-provenance
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3.2.0
        with:
          subject-path: _build/default/bin/rebar3_dependency_submission

      - name: Copy provenance
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: >-
          cp "${{ steps.attest-provenance.outputs.bundle-path }}"
             _build/default/bin/rebar3_dependency_submission.sigstore

      - name: Create a GitHub release
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: >-
          gh release create
            --generate-notes
            "${{ inputs.tag }}"
            _build/default/bin/rebar3_dependency_submission*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
