---
name: Release
# Release a new version: prior to this you should've updated references to release-TAG

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/release
        with:
          tag: ${{ inputs.tag }}
          github_actor: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
